version: '3.5'

services:

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'events_anomaly'
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD:

  adminer:
    image: adminer
    ports:
    - 8080:8080

volumes:
  data:

networks:
  default:
    external:
      name: sg_lambda_integration_default