AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deploy
  SAM Template for deploy lambda
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3


Resources:

  DeployFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: function.lambda_handler
      Runtime: python3.7
      Timeout: 300
sw      Environment:
        Variables:
          MODEL_PREFIX: linear_learner
          ENDPOINT_PREFIX: linear_learner
      Events:
        DeployEndpoint:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /deploy
            Method: get

Outputs:

  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DeployApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cea/"

  DeployFunction:
    Description: "Listener Sim Lambda Function ARN"
    Value: !GetAtt DeployFunction.Arn

  DeployFucntionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt DeployFunctionRole.Arn