AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  listener_sim
  SAM Template for listener_sim lambda
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3


Resources:

  ListenerSimFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: function.lambda_handler
      Runtime: python3.7
      Timeout: 300
      Environment:
        Variables:
          DATABASE: events_anomaly
          DB_USER:
          PASSWORD:
          PORT: 3306
          HOST: docker.for.mac.host.internal
      Events:
        ListenerSimEndpoint:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /listener_sim
            Method: get
        ListenerSimEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: {}

Outputs:

  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ListenerSimApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cea/"

  ListenerSimFunction:
    Description: "Listener Sim Lambda Function ARN"
    Value: !GetAtt ListenerSimFunction.Arn

  ListenerSimFucntionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt ListenerSimFunctionRole.Arn